### ISSUE TITLE
Unable to connect to Metamask

### ISSUE THREAD

**Issue by prashantprabhakar** [ethereum/remix-ide#1329]
I was trying to connect remix with Metamask. When I change provider from Javascript VM to Injected Web3m I get error:

> Cannot get account list: Error: Invalid JSON RPC response: {"id":46,"jsonrpc":"2.0","error":{"code":-32603}}

While metamask injected web3 in browser. I could use web3.accounts in browser console. 

While this was working before. I have used this 10000 times. Not sure if something is broken.

**Comment by yann300** [comment]
could be something with infura's node.. is this fixed now?

**Comment by yann300** [comment]
closing now . please double check again, I think that was an issue with infura's node

**Comment by prashantprabhakar** [comment]
No. The issue still persists. I am getting the same response, when I try to connect to metamask.
URL: https://remix.ethereum.org/#optimize=false&version=soljson-v0.4.24+commit.e67f0147.js
Metamask is connected to ropsten network.
`{code: -32603, message: "Internal JSON-RPC error."}`

**Comment by shivamti** [comment]
I am experiencing the same issue! 
inpage.js:1 MetaMask - RPC Error: Internal JSON-RPC error. Objectcode: -32603message: "Internal JSON-RPC error."__proto__: Object
(anonymous) @ inpage.js:1

**Comment by shivamti** [comment]
@yann300 please open this issue again. Restarting browser doesnt work

**Comment by yann300** [comment]
could you switch network in metamask. I think that an issue with the rpc layer used by metamask

**Comment by ayang99** [comment]
I'm still experiencing this in Remix Browser. I've updated Metamask and switched between Ropsten and Rinkeby. I've restarted Chrome and uninstalled/reinstalled Metamask.

**Comment by danfinlay** [comment]
Hi @ayang99 and @shivamti, I'm on the MetaMask team.

The error you're hitting is our most opaque one, and is internally generated, so it's hard to tell what's happening from it. Could be a firewall, could be some internal bug we aren't aware of yet.

It might be worth [opening an issue with MetaMask](https://github.com/MetaMask/metamask-plugin/issues) directly, where you can document any debugging procedures. It will likely involve opening a background console to look for error messages:
https://consensys.zendesk.com/hc/en-us/articles/360004134112-How-To-Get-Logs-And-Help-MetaMask-Support-and-Diagnose-Your-Issue

**Comment by codeinstinct** [comment]
Has this issue been resolved ? If yes, please share links to the solution.

**Comment by jmis0532** [comment]
change your metamask settings Security & Privacy and turn off Privacy Mode.

**Comment by qugang** [comment]
use http://remix.ethereum.org  
Do not use https://remix.ethereum.org

**Comment by StupidRin** [comment]
> use http://remix.ethereum.org
> Do not use https://remix.ethereum.org
I resolved it by using  http://remix.ethereum.org and turning off Privacy Mode.

**Comment by RockmanR** [comment]
I've used the 'http' and turned off the privacy, but the problem still exists.
