### ISSUE TITLE
Javascript console errors running Remix-IDE locally

### ISSUE THREAD

**Issue by prd-fox** [ethereum/remix-ide#1770]
When cloning and running Remix IDE locally, I am unable to submit transactions (contract deployments) due to the following 2 errors in the JS console:

>Uncaught TypeError: Cannot read property 'getUnpersistedProperty' of undefined
>Uncaught TypeError: Cannot read property 'get' of undefined

which stem from `api.personalMode()` and `self._api.config.getUnpersistedProperty('doNotShowTransactionConfirmationAgain')` in [txRunner.js](https://github.com/ethereum/remix/blob/master/remix-lib/src/execution/txRunner.js).

To reproduce, I performed the following steps (as per the README):
```
git clone https://github.com/ethereum/remix-ide.git
cd remix-ide
npm install
npm start
```
and then connected to a local node and tried deploying a contract.

The same happened if I linked remix-lib etc, but left it out here for simplicity.

Did I miss a step or get something wrong to cause this?

**Comment by yann300** [comment]
thanks for the report,
in the meantime, could you checkout the commit of https://github.com/ethereum/remix-ide/releases/tag/v0.7.6 (that's the lastest release)

**Comment by prd-fox** [comment]
That works, so it's just an issue with master.

Thanks!

**Comment by yann300** [comment]
just so we can make sure to fix it, does that happen using javascript VM, injected provider or web3 provider?
cc @LianaHus

**Comment by prd-fox** [comment]
Both 'Injected Web3' and 'Web3 Provider' have this issue. Javascript VM works fine.

**Comment by wjmelements** [comment]
I am seeing the same issue, with injected web3 from MetaMask.

**Comment by yann300** [comment]
the fix is deployed to the branch `swap_it` which is our develop branch

**Comment by oogetyboogety** [comment]
@yann300 still receiving this error on the swap_it branch with Environment set to Web3 Provider
