### ISSUE TITLE
Contract compilation stalls due to static analysis on Alpha Remix

### ISSUE THREAD

**Issue by D-Nice** [ethereum/remix-ide#2029]
Trying to compile the following contract: https://raw.githubusercontent.com/oraclize/ethereum-examples/master/solidity/KrakenPriceTicker.sol

with solidity on the Alpha version of remix, causes the compilation to stall out. The culprit appears to be the solidity static analyzer based on the following console log output:

```
Uncaught TypeError: item.location.split is not a function
    at app.js:265263
    at Array.map (<anonymous>)
    at app.js:265258
    at Array.map (<anonymous>)
    at app.js:265257
    at staticAnalysisRunner.runWithModuleList (app.js:174699)
    at staticAnalysisRunner.run (app.js:174664)
    at staticAnalysisView.run (app.js:265256)
    at Object.<anonymous> (app.js:265214)
    at eventManager.trigger (app.js:194345)
    at EventEmitter.PluginManagerProxy._listeners.solidity (app.js:257906)
    at emitMany (app.js:47305)
    at EventEmitter.emit (app.js:47360)
    at Object.<anonymous> (app.js:265554)
    at eventManager.trigger (app.js:194345)
    at compilationFinished (app.js:200146)
    at compileJSON (app.js:200023)
    at app.js:199976
    at gatherImports (app.js:200274)
    at app.js:200266
    at app.js:265976
    at app.js:256833
```

Disabling the static analyzer from auto-running results in fine and successful compilation.

**Comment by LianaHus** [comment]
thanks for the report

**Comment by LianaHus** [comment]
https://github.com/ethereum/remix/pull/1210

**Comment by yann300** [comment]
^ fix merged

**Comment by D-Nice** [comment]
As a note, I am still having the issue, having tried remix-alpha page (cleared cache)

![2019-06-19-103928_1762x1021_scrot](https://user-images.githubusercontent.com/2888248/59775324-068e4600-927f-11e9-92c2-28d1ee4f0838.png)

Also, deactivating the analyzer, doesn't actually seem to unhook it, as one may expect. In that, if you deactivate the analyzer, but don't tick off auto-run, it actually still runs.

**Comment by yann300** [comment]
hmm the fix was merged... do you have the same in remix.ethereum.org?

**Comment by yann300** [comment]
i see that the issue is still there, going to make a patch release asap, thanks for the feedback

**Comment by yann300** [comment]
latest remix IDE was not using latest remix-analyzer. that fixed now, please confirm

**Comment by D-Nice** [comment]
Thanks for quick response. All working good now :+1:
